# Default encoding configuration for WiMAE and ContraWiMAE

# Model configuration
model:
  checkpoint_path: "checkpoints/model.pt"
  device: "cuda"
  
  # Override model parameters if needed
  patch_size: [4, 4]
  encoder_dim: 256
  encoder_layers: 12
  encoder_nhead: 8
  decoder_layers: 8
  decoder_nhead: 8
  mask_ratio: 0.75

# Encoding configuration
encoding:
  batch_size: 256
  num_workers: 4
  pin_memory: true
  
  # Output options
  output_format: "pt"  # Options: "pt", "npz", "npy"
  output_dir: "embeddings"
  
  # Pooling method for embeddings
  pooling: "mean"  # Options: "mean", "cls", "max"
  
  # Save options
  save_embeddings: true
  save_reconstructions: false
  save_contrastive_features: false  # Only for ContraWiMAE
  
  # Memory management
  use_gradient_checkpointing: false
  use_amp: true

# Data configuration
data:
  data_path: "path/to/data"
  data_format: "npz"
  channels: 2
  height: 64
  width: 64
  
  # Data subset
  subset: "all"  # Options: "all", "train", "val", "test"
  max_samples: null  # Set to limit number of samples

# Output configuration
output:
  # File naming
  filename_prefix: "embeddings"
  include_timestamp: true
  
  # Metadata
  save_metadata: true
  metadata_fields: ["model_info", "encoding_params", "data_info"]
  
  # Compression
  compression: false  # For npz format
  
# Logging configuration
logging:
  verbose: true
  progress_bar: true
  log_interval: 100 