# Default downstream task configuration for WiMAE and ContraWiMAE

# Model configuration
model:
  checkpoint_path: "checkpoints/wimae/model.pt"
  device: "cuda:0"
  pooling: "mean"  # Options: "mean", "cls", "max"

# Task configuration
task:
  type: "beam_prediction"  # Options: "beam_prediction", "los_classification"
  
  # Beam prediction specific
  codebook_size: 16  # Options: 16, 32, 64, 128, 256
  
  # LOS classification specific
  threshold: 0.5  # Decision threshold for binary classification

# Training configuration
training:
  batch_size: 512
  learning_rate: 0.0001
  weight_decay: 1e-5
  epochs: 5000
  val_split: 0.2
  test_split: 0.1
  
  # Training budget (fraction of training data to use)
  training_budget: 1.0
  
  # Optimization
  optimizer: "adam"
  scheduler: "exponential"  # Options: "step", "exponential", "plateau", "cosine"
  scheduler_params:
    gamma: 0.95  # For exponential scheduler
  
  # Early stopping
  early_stopping_patience: 50
  early_stopping_min_delta: 1e-6
  
  # Fine-tuning options
  fine_tune_encoder: false  # Whether to fine-tune the encoder
  encoder_lr_multiplier: 0.1  # Learning rate multiplier for encoder

# Data configuration
data:
  # Input data (embeddings or raw data)
  input_type: "embeddings"  # Options: "embeddings", "raw"
  
  # For embeddings
  embeddings_path: "embeddings/embeddings.pt"
  
  # For raw data
  data_path: "data/test/channels.npz"
  data_format: "npz"
  
  # Labels
  labels_path: "data/test/bp_labels_28ghz.pt"
  label_type: "beam_prediction"  # Options: "beam_prediction", "los"
  
  # Data loading
  num_workers: 4
  pin_memory: true
  shuffle: true

# Model architecture
architecture:
  type: "linear"  # Options: "linear", "fcn", "resnet"
  
  # Linear model
  hidden_dim: 64
  
  # FCN model
  layers: [512, 256, 128]
  dropout: 0.1
  activation: "relu"
  
  # ResNet model
  num_blocks: 3
  block_channels: [64, 128, 256]
  block_layers: [2, 2, 2]

# Evaluation configuration
evaluation:
  # Metrics
  metrics:
    beam_prediction: ["top1_accuracy", "top3_accuracy", "cross_entropy"]
    los_classification: ["accuracy", "precision", "recall", "f1", "auc", "specificity", "npv"]
  
  # Evaluation settings
  eval_batch_size: 512
  save_predictions: false
  confusion_matrix: true

# Output configuration
output:
  output_dir: "results"
  save_model: true
  save_metrics: true
  save_predictions: false
  
  # File naming
  filename_prefix: "results"
  include_timestamp: true

# Logging configuration
logging:
  verbose: true
  progress_bar: true
  log_interval: 100
  tensorboard: false 