# Scenario Split Configuration
# This config defines file patterns for train/val/test splits
# Other parameters (normalize, statistics, etc.) are handled in the main training config

# Training patterns - files to use for training
train_patterns:
  # Urban scenarios
  - "urban.*\.npz"           # All urban scenario files
  - "city.*\.npz"            # City environment files
  - "dense.*\.npz"           # Dense urban files
  
  # Indoor scenarios
  - "indoor.*\.npz"          # Indoor environment files
  - "office.*\.npz"          # Office environment files
  - "home.*\.npz"            # Home environment files
  
  # Suburban scenarios
  - "suburban.*\.npz"        # Suburban environment files
  - "residential.*\.npz"     # Residential area files

# Validation patterns - files to use for validation
val_patterns:
  # Rural scenarios
  - "rural.*\.npz"           # Rural environment files
  - "countryside.*\.npz"     # Countryside files
  
  # Highway scenarios
  - "highway.*\.npz"         # Highway environment files
  - "motorway.*\.npz"        # Motorway files

# Test patterns - files to use for testing
test_patterns:
  # Mixed scenarios
  - "mixed.*\.npz"           # Mixed environment files
  - "test.*\.npz"            # Test scenario files

# Alternative patterns for different naming conventions:
# Uncomment the section that matches your file naming:

# Simple numbered files: data_0.npz, data_1.npz, etc.
# train_patterns:
#   - "data_[0-6]\.npz"       # Files 0-6 for training
# val_patterns:
#   - "data_[78]\.npz"        # Files 7-8 for validation
# test_patterns:
#   - "data_9\.npz"           # File 9 for testing

# SNR-based splits
# train_patterns:
#   - ".*snr_[0-9]_.*\.npz"   # Low SNR files for training
#   - ".*snr_1[0-9]_.*\.npz"  # Medium SNR files for training
# val_patterns:
#   - ".*snr_2[0-4]_.*\.npz"  # High SNR files for validation
# test_patterns:
#   - ".*snr_2[5-9]_.*\.npz"  # Very high SNR files for testing

# Frequency-based splits
# train_patterns:
#   - ".*freq_2[0-9].*\.npz"  # 2.x GHz files for training
#   - ".*freq_3[0-9].*\.npz"  # 3.x GHz files for training
# val_patterns:
#   - ".*freq_4[0-4].*\.npz"  # 4.0-4.4 GHz files for validation
# test_patterns:
#   - ".*freq_4[5-9].*\.npz"  # 4.5-4.9 GHz files for testing 