# Training configuration for WiMAE and ContraWiMAE with Scenario Split

# Model configuration
model:
  type: "contramae"  # Options: "wimae", "contramae"
  patch_size: [1, 16]
  encoder_dim: 64
  encoder_layers: 12
  encoder_nhead: 16
  decoder_layers: 4
  decoder_nhead: 12
  mask_ratio: 0.6
  contrastive_dim: 64
  temperature: 0.1
  snr_min: 0.0
  snr_max: 30.0

# Data configuration with Scenario Split
data:
  # Data directory containing NPZ files
  data_dir: "data/pretrain"
  
  # Normalization settings
  normalize: true
  val_split: 0.2
  debug_size: null  # Set to a number for debugging (e.g., 1000)
  
  # Statistics handling options:
  # Option 1: Calculate statistics on-the-fly from training data
  calculate_statistics: true  # Calculate from training data
  
  # Option 2: Use pre-computed statistics (used if calculate_statistics=false)
  # statistics:
  #   real_mean: 0.021121172234416008
  #   real_std: 30.7452392578125
  #   imag_mean: -0.01027622725814581
  #   imag_std: 30.70543670654297
  
  # Scenario split configuration
  scenario_split_config: "configs/scenario_split_simple.yaml"
  # scenario_split_config: "configs/scenario_split_test.yaml"

# Training configuration
training:
  batch_size: 64
  epochs: 100
  num_workers: 4
  device: "cuda:0"
  
  optimizer:
    type: "adamw"
    lr: 0.0001
    weight_decay: 0.01
    betas: [0.9, 0.999]
  
  scheduler:
    type: "cosine"
    T_max: 100
    eta_min: 0.000001
  
  loss: "mse"
  
  # Early stopping
  patience: 20
  min_delta: 0.001
  
  # Checkpointing
  save_checkpoint_every_n: 10
  save_best_only: true

# Logging configuration
logging:
  log_dir: "runs"
  tensorboard: true
  log_every_n_steps: 100 